[project]
name = "myproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "joblib<1.3.0",
    "numpy<1.27",
    "pycaret>=3.3.0",
    "scikit-learn<1.5.0",
]
